//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odev
    {
        public string odevId { get; set; }
        public string odevAdi { get; set; }
        public string odevDersId { get; set; }
    
        public virtual Ders Ders { get; set; }
    }
}
